### ISSUE TITLE
Arabic issue

### ISSUE THREAD

**Issue by ZiyadNabil** [iAmAsval/FModel#102]
Hey, there is an issue when i extract challenges or anything in arabic its not correct hope u guys can solve it fast cuz i really want it to be solved

Mikey knows how Arabic words works maybe he can fix it and thanks 😊

**Comment by iAmAsval** [comment]
Arabic is broken but also break everything else.
When i "fix it", centered texts don't work anymore, hence breaks all other languages texts position and custom fonts don't work anymore either.

Here is an example
![image](https://user-images.githubusercontent.com/26126862/90742495-c0dc6b80-e2cf-11ea-8818-5e30ce5d3a12.png)

**Comment by ZiyadNabil** [comment]
So u cant fix it?
Cuz im a leaker and i really want to upload it to my followers in Arabic instead of English please find a way to solve this please

**Comment by iAmAsval** [comment]
I can't fix it at the moment

**Comment by GMatrixGames** [comment]
Thanks to @NotOfficer, this issue is now closed.
