### ISSUE TITLE
List Package/UObject GUID on file details panel.

### ISSUE THREAD

**Issue by Cyuubi** [iAmAsval/FModel#107]

**Comment by iAmAsval** [comment]
wdym with UObject guid? can he be grabbed before the extract process begins?

**Comment by iAmAsval** [comment]
.

**Comment by iAmAsval** [comment]
I need more info

**Comment by FabianFG** [comment]
I'm pretty sure you can't get it without serializing the assets

**Comment by iAmAsval** [comment]
what even is that GUID
do uobjects always have a GUID?

**Comment by FabianFG** [comment]
There is a packageGuid for each FObjectExport. I think that's what this is about

**Comment by iAmAsval** [comment]
ah ok i see

**Comment by FabianFG** [comment]
And inside a UObject there also is an objectGuid serialized
