### ISSUE TITLE
How do I make it actually use an Output folder next to the EXE file?

### ISSUE THREAD

**Issue by Videogamer555** [iAmAsval/FModel#114]
According to the official documentation, it puts everything in a folder called Output, right next to the EXE file, but it's NOT exhibiting this behavior. Instead it's putting everything in %TEMP%\Output no matter WHERE I have the EXE file. Yes, for testing, I INITIALLY had the EXE file in %TEMP%, but since then I moved it, and I even deleted the settings file located in the %APPDATA%\FModel folder. Yet FModel keeps INSISTING on outputing EVERYTHING to %TEMP%\Output and I DO NOT WANT THAT.

PLEASE tell me how to make it actually follow the official documentation, and create a folder called Output next to its EXE file, and put everything in THAT Output folder.

**Comment by iAmAsval** [comment]
Change the output path in the settings

**Comment by Videogamer555** [comment]
I tried that. It seems to be ignoring the settings file. Also, your official documentation simply says that it will automatically use an output folder next to the EXE file. It DOES NOT do this. It's NOT LOOKING GOOD, when a developer writes a program to behave DIFFERENTLY than the OFFICIAL DOCUMENTATION states it will.

**Comment by iAmAsval** [comment]
if there's a setting window it's because the software settings are their especially what you're looking for `Extraction Path`
I'm sorry if you think the readme is a doc, I could write an actual doc but nobody would read it anyway
![image](https://user-images.githubusercontent.com/26126862/95629537-67e3b500-0a80-11eb-809c-e303802bf14f.png)

**Comment by FabianFG** [comment]
Relax, maybe try to delete all FModel settings files and run it again
