### ISSUE TITLE
Add an "AES Manager"

### ISSUE THREAD

**Issue by AyeTSG** [iAmAsval/FModel#12]
What this would let you do is the following:

- Save multiple AES keys
- If a pak won't open with one key, try every other key saved (this will repeat until a pak key cannot decrypt. In this case, it will try every other key again. If it cannot be decrypted, it will give the usual key error)

**Comment by AyeTSG** [comment]
Requesting approval from @iAmAsval

**Comment by iAmAsval** [comment]
Good idea, we could also switch to this method later to backup dynamic paks as the current one isn't that good
Approved

**Comment by AyeTSG** [comment]
Closing due to approval.
