### ISSUE TITLE
Tried to connect to dropbox?!

### ISSUE THREAD

**Issue by petrarislin** [iAmAsval/FModel#127]
On first running, Norton detected an outbound TCP to a dropbox address. Extremely suspicious...

**Comment by iAmAsval** [comment]
it's open source for a reason...

**Comment by iAmAsval** [comment]
it doesn't try to connect to dropbox, it makes a get request on a dropbox link

**Comment by FabianFG** [comment]
`public const string FMODEL_JSON = "https://dl.dropbox.com/s/sxyaqo6zu1drlea/FModel.json?dl=0";` ([Here](https://github.com/iAmAsval/FModel/blob/master/FModel/Utils/Endpoints.cs#L19))

**Comment by blobry** [comment]
> `public const string FMODEL_JSON = "https://dl.dropbox.com/s/sxyaqo6zu1drlea/FModel.json?dl=0";` ([Here](https://github.com/iAmAsval/FModel/blob/master/FModel/Utils/Endpoints.cs#L19))
> 
> Used two times: 1. [For grabbing the FModel cdn](https://github.com/iAmAsval/FModel/blob/master/FModel/Grabber/Cdn/CdnData.cs#L18)
> 2. [In the auto updater](https://github.com/iAmAsval/FModel/blob/master/FModel/Utils/Updater.cs#L17)

Omg hes hacking fmodel delete fmodel!!! besides jokes you has big brain
