### ISSUE TITLE
[Bug?] Configuration System Failed to install on a fresh install of fmodel

### ISSUE THREAD

**Issue by TheBaconSpace** [iAmAsval/FModel#129]
![Fmodel Error](http://puu.sh/GG5q5/805c44184e.png)
Hello So i Installed the Net Core and it worked fine then i got this when i tried to boot it back up im on windows 10

**Comment by iAmAsval** [comment]
can you send the log file that goes with it?
also, do you run the release version or you build it?

**Comment by TheBaconSpace** [comment]
could you direct me where i could find the log ?

**Comment by iAmAsval** [comment]
Output/Logs/
if fmodel is open, press F3 to open the ouput folder, else it should be where the exe is

**Comment by iAmAsval** [comment]
might be worth to try a setting reset too
delete appdata/roaming/fmodel and appdata/local/asval

**Comment by TheBaconSpace** [comment]
**delete appdata/roaming/fmodel and appdata/local/asval** worked thank you so much

**Comment by iAmAsval** [comment]
noice

**Comment by TheBaconSpace** [comment]
you still want the logs

**Comment by iAmAsval** [comment]
na it's fine

**Comment by TheBaconSpace** [comment]
[FModel-Log-2020-10-23.txt](https://github.com/iAmAsval/FModel/files/5431685/FModel-Log-2020-10-23.txt)
