### ISSUE TITLE
[14.40+ / ZenLoader] FileList backups do not work as expected

### ISSUE THREAD

**Issue by AyeTSG** [iAmAsval/FModel#131]
When loading a FileList backup from a version prior to the ZenLoader implementation, FModel will hang for upwards of a minute and a half, and then the diff files do not display as they should.

**Comment by FabianFG** [comment]
Backups aren't implemented for the new format

**Comment by blobry** [comment]
close dis issaue

**Comment by AyeTSG** [comment]
@blobry Please do not request issues to be closed, as this is essentially a pinned not that the feature does not work as it should. The issue will be closed once everything works as it should.

**Comment by blobry** [comment]
> @blobry Please do not request issues to be closed, as this is essentially a pinned not that the feature does not work as it should. The issue will be closed once everything works as it should.

big boy words but ok i understand

**Comment by iAmAsval** [comment]
forgot to close this while committing
