### ISSUE TITLE
cannot view fortnite 14.0 files

### ISSUE THREAD

**Issue by TheBlindeFortnite** [iAmAsval/FModel#135]
Hi, so i'm a blind game developer who uses the fortnite sounds. I wanted to view the fortnite 14.0 files to find the pickaxe sounds, weapon sounds, and the new marvle  mythic sounds. It says I have to build the repository but I don't know how to do that. Can I download the release and it would still work?

**Comment by jose89fcb** [comment]
Hello, if you enter fmodel official discord you will find a section called "announcements" there you can find the already built program



sorry my english xD
