### ISSUE TITLE
Opening certain playlists heavily increases the ram usage.

### ISSUE THREAD

**Issue by Slushia** [iAmAsval/FModel#142]
Opening certain playlist files increases the ram from around 1gb to 16-20gb in my case, and it also happened to other people I asked.

An example of this is `Playlist_Papaya`(`FortniteGame/Content/Athena/Playlists/Papaya/Playlist_Papaya.uasset`), as shown below.
![Ram Usage](https://user-images.githubusercontent.com/56281030/99887786-742d6700-2c15-11eb-80c2-236bb16254f3.png)

**Comment by wiktorwiktor12** [comment]
how

**Comment by blobry** [comment]
Must be your pc.

**Comment by AyeTSG** [comment]
> 
> 
> Must be your pc.

This is incorrect. This is an issue with FModel itself.

**Comment by blobry** [comment]
bro just install more ram 🙄

**Comment by AyeTSG** [comment]
> 
> 
> bro just download more ram 🙄

Please do not comment on issues relating to FModel if you have nothing to contribute to the bug report.

**Comment by blobry** [comment]
This has happened to me lately, seems to happen with other things like big JSON files or what not.

**Comment by voxxid** [comment]
when ram use

**Comment by iAmAsval** [comment]
just tried all playlists, it's fixed and was due to bad mapping
