### ISSUE TITLE
Support for other games pre-UE4.19

### ISSUE THREAD

**Issue by IgelRM** [iAmAsval/FModel#145]
Games that use older UE4 PAK versions produce the error "Bad state (unknown compression method (0x00)" when trying to open UASSETs. (Ideally FModel would support [all UE4 PAK versions](https://gbatemp.net/threads/how-to-unpack-and-repack-unreal-engine-4-files.531784/). Since UE4.19, there appear to be non-backwards compatible changes to the format with each version)

A corresponding version of UnrealPak can be used to extract the UASSETS, but these cannot be loaded in FModel. Request: Add an option to treat a folder as a PAK root.

I tested FModel with 'Tell Me Why' and the JSON Viewer works well, thank you for this project. But Life is Strange 2 (UE4.16) produced the above PAK error.

**Comment by blobry** [comment]
Yeah true, but it might take a little bit to add all of the PAK versions, also isn't UE5 coming soon?

**Comment by iAmAsval** [comment]
I can already say that extracted uasset support will not come to fmodel 4 because it's a mess to handle in the UI, but the next parser does support this kind of behaviour by default and can then gives you a json of the asset's properties.

**Comment by IgelRM** [comment]
Can you clarify "this kind of behaviour", will the parser and JSON Viewer be able to work separately or are planning to support older PAK formats?

I know there is already [SirWaddles/JohnWickParse](https://github.com/SirWaddles/JohnWickParse) but it errors out on a lot of UASSETs and is rather cumbersome to use.

**Comment by FabianFG** [comment]
The new parser supports all pak versions and also offers more dynamic version selection support for parsing assets. Additionally it will also be able to parse local uassets that are located in the selected directory.

**Comment by Muzzarino** [comment]
> The new parser supports all pak versions and also offers more dynamic version selection support for parsing assets. Additionally it will also be able to parse local uassets that are located in the selected directory.

We have a Spyro Reignited modding server that might want this because extracting paks wastes space especially on low memory computers. So FModel should Spyro Reignited Trilogy that can be made part of the community to extract single files using this tool. It's discord server is [.](https://discord.gg/Yy4SMkn)

**Comment by Beat-YT** [comment]
nah

**Comment by Muzzarino** [comment]
> nah

We need this extractor as a tool to extract a single file to save disk space rather than unpacking the entire pak when making mods for the game.

**Comment by Beat-YT** [comment]
Your lazy, do it yourself, he is not your self, now close this issue

**Comment by Beat-YT** [comment]
> > nah
> 
> We need this extractor as a tool to extract a single file to save disk space rather than unpacking the entire pak when making mods for the game.

It's not for mod

**Comment by Beat-YT** [comment]
> > The new parser supports all pak versions and also offers more dynamic version selection support for parsing assets. Additionally it will also be able to parse local uassets that are located in the selected directory.
> 
> We have a Spyro Reignited modding server that might want this because extracting paks wastes space especially on low memory computers. So FModel should Spyro Reignited Trilogy that can be made part of the community to extract single files using this tool. It's discord server is https://discord.gg/Yy4SMkn.

No one care about this game, fmodel is for fortnite

**Comment by iAmAsval** [comment]
@Beat-YT nobody asked for your opinion
If it's to make useless comments, keep them for you

**Comment by GMatrixGames** [comment]
Can be resolved with CUE4Parse when it releases. Closing
