### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by Tubitex** [iAmAsval/FModel#146]
Every time when I want to work with Fmodel and loading the backup etc then I go on directories and Cosmetics it only goes to the file "Content". It is so since the new update

**Comment by iAmAsval** [comment]
[first line](https://github.com/iAmAsval/FModel/releases/tag/3.1.1.3)

**Comment by Tubitex** [comment]
?

**Comment by iAmAsval** [comment]
![image](https://user-images.githubusercontent.com/26126862/102192852-9ab08c00-3ebb-11eb-9abf-c120c8d67e8c.png)

**Comment by iAmAsval** [comment]
https://ci.appveyor.com/project/iAmAsval/fmodel/branch/master/artifacts

**Comment by Tubitex** [comment]
omg thank you <3
