### ISSUE TITLE
Backup paks not there.

### ISSUE THREAD

**Issue by Rxyn49** [iAmAsval/FModel#148]
when i try to open new files it tells me to select  a back up pak but i cannot see and cant download one either
![2020-12-22 (2)](https://user-images.githubusercontent.com/76459740/102839660-d6e76d80-4422-11eb-9a78-c28457ea9fa3.png)

**Comment by GMatrixGames** [comment]
Select a game in the settings tab

**Comment by Rxyn49** [comment]
> Select a game in the settings tab

still cant see it

**Comment by iAmAsval** [comment]
redownload or set a game or send log file

**Comment by Rxyn49** [comment]
> redownload or set a game or send log file

still no luck

**Comment by iAmAsval** [comment]
**or send log file**

**Comment by Rxyn49** [comment]
I found the files thank you for your  time
