### ISSUE TITLE
Can't find Cosmetics 

### ISSUE THREAD

**Issue by TheHarleyQuinn** [iAmAsval/FModel#149]
Greetings everyone, So recently I just learned about The FModel and how you can mine the Fortnite data I saw some guides from u/iFireMonkey and u/TheGameVlog They were awesome Until I've found that I don't have any Cosmetics in my Fortnite, I just have these folders nothing else I didn't find anything else Is something wrong with my game? I've verified my game and searched in my Fortnite folder I don't have that folder by the way...

![123](https://user-images.githubusercontent.com/77130440/103958187-a19c8880-5161-11eb-9494-acd7fd57ed6e.PNG)

**Comment by GMatrixGames** [comment]
Update FModel
