### ISSUE TITLE
Could not find a part of the path 'dir where the fmodel was located before on a removed drive'

### ISSUE THREAD

**Issue by Longhouse81** [iAmAsval/FModel#151]
I removed a disk from PC where Fmodel was located before, i tried everything, download it again etc but i keep getting this error it tries to read from that disk and can't find anywhere a registry entry that i can change or delete "Could not find a part of the path 'dir where the fmodel was located before on a removed drive\'."

Any ideas where to find the registry entry or something i can do to fix this error

Thanks

**Comment by NotOfficer** [comment]
Try to delete this folder: `%appdata%\FModel`

**Comment by Longhouse81** [comment]
Still same error
![image](https://user-images.githubusercontent.com/69700930/104112564-9fb4ff80-52f0-11eb-9b13-0310f98de714.png)

**Comment by Longhouse81** [comment]
Fixed, it creates an entry under local APPDATA too, removed it and forks fine, Thank you
