### ISSUE TITLE
If i Open Big PAK files or Sources FModel Is Crashing

### ISSUE THREAD

**Issue by HarlenY** [iAmAsval/FModel#155]
Bug Example `"If i Open Big PAK files or Sources FModel Is Crashing"`

I Dont Have a Log File Because Program Is `Crashing `And `Closing`

**Comment by iAmAsval** [comment]
what is a big pak file?
what is source?

**Comment by HarlenY** [comment]
Valorant Pak Files

**Comment by HarlenY** [comment]
if i want extract all pak files program is crashing

**Comment by iAmAsval** [comment]
why would you want to do that

**Comment by iAmAsval** [comment]
please provide the log file...
it's created at launch no matter if you crash or not
