### ISSUE TITLE
can't extract or listen 

### ISSUE THREAD

**Issue by SS4K** [iAmAsval/FModel#156]
at first the program asked for oo2core_8_win64.dll , i took oo2core_5_win64.dll form the game file then renamed it

every time i try to listen e.g MusicPack_Envy_Cue.uasset i got error 
[
  {
    "ExportType": "SoundCue",
    "ExportValue": null
  },
  {
    "ExportType": "SoundNodeWavePlayer",
    "ExportValue": null
  }
]

also can't extract anything 
[FModel-Log-2021-02-01.txt](https://github.com/iAmAsval/FModel/files/5902233/FModel-Log-2021-02-01.txt)

**Comment by NotOfficer** [comment]
Works just fone for me, try to redownload FModel [here](https://github.com/iAmAsval/FModel/releases/latest) and use this oodle dll: [oo2core_8_win64.zip](https://github.com/iAmAsval/FModel/files/5902390/oo2core_8_win64.zip).

**Comment by SS4K** [comment]
> 
> 
> Works just fine for me, try to redownload FModel [here](https://github.com/iAmAsval/FModel/releases/latest) and use this oodle dll: [oo2core_8_win64.zip](https://github.com/iAmAsval/FModel/files/5902390/oo2core_8_win64.zip).

still the same problem, last time i was using FModel on ver 3.1.1.1 and i have no problem with it

**Comment by iAmAsval** [comment]
no mappings, no asset
restart fmodel

**Comment by iAmAsval** [comment]
or download [this](https://benbotfn.tk/api/v1/mappings/++Fortnite+Release-15.21-CL-15083856-Windows_br.usmap) and put it in `/Output/PakChunks/`

**Comment by SS4K** [comment]
> 
> 
> or download [this](https://benbotfn.tk/api/v1/mappings/++Fortnite+Release-15.21-CL-15083856-Windows_br.usmap) and put it in `/Output/PakChunks/`

OMG it works now , thank you for the awesome program

does your program have access to STW dialog/voiceline ?

**Comment by iAmAsval** [comment]
it has what your game has

**Comment by SS4K** [comment]
> 
> 
> it has what your game has

thank you , i found everything i need

**Comment by SS4K** [comment]
one last thing

 PakChunks/oo2core_8_win64.dll should be part of installation guide

for less confusing

**Comment by iAmAsval** [comment]
oo2core_8_win64 shouldn't be in PakChunks and it's downloaded automatically if needed

**Comment by SS4K** [comment]
> 
> 
> oo2core_8_win64 shouldn't be in PakChunks and it's downloaded automatically if needed
i know, typing error, & instead /
oo2core_8_win64 with .exe

also my bad FModel.exe was blocked from accessing the internet *_*

i did a test with internet and it downloads everything with problem

make it part of the guide ,  exe need to access internet 

sorry for wasting your time
