### ISSUE TITLE
Valorant 2.02

### ISSUE THREAD

**Issue by zeuxis69** [iAmAsval/FModel#157]
Unable to extract models after the recent VALORANT Update.

It shows "Unable to read beyond the end of stream" error.

Log File - [FModel-Log-2021-02-04.txt](https://github.com/iAmAsval/FModel/files/5922115/FModel-Log-2021-02-04.txt)

Screenshot - ![image](https://user-images.githubusercontent.com/61117363/106822260-d3433980-66a4-11eb-82dc-a8933dda6c75.png)

**Comment by RumbleMike** [comment]
Download the newest version from here: https://ci.appveyor.com/project/iAmAsval/fmodel/builds/37578544/artifacts  This should fix the current issue you have.
