### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by DeathKilledU2** [iAmAsval/FModel#159]
The challenges are in the packages, but arent showing what the actual challenges are (the actual challenges is there but in the photo that it shows it has no challenges on it)
![image](https://user-images.githubusercontent.com/66250882/107844625-b9ca8c00-6e20-11eb-8e44-2bea11698d21.png)

**Comment by iAmAsval** [comment]
I am not responsible for your own directories nor for the outdated sate the challenge path might be
