### ISSUE TITLE
Can't export WwiseAudio from VALORANT

### ISSUE THREAD

**Issue by PastaDogFX** [iAmAsval/FModel#164]
Hi all,

I am trying to export the Sovereign Kill Sound from VALORANT's files. When I click Extract on the file, it says "Unable to read beyond end of stream". When I click Export, it just exports a .uasset file which is kind of useless when you want to get the audio. What can I do to export the audio file?

Thanks,
Pasta

**Comment by iAmAsval** [comment]
https://ci.appveyor.com/project/iAmAsval/fmodel/branch/master/artifacts

**Comment by PastaDogFX** [comment]
Thank you!
