### ISSUE TITLE
Quick Save Function

### ISSUE THREAD

**Issue by britiscurious** [iAmAsval/FModel#166]
When I want to export *.json assets I usually select an upper level folder, right click and choose "Extract" whil having the option "Assets / Auto / Save" enabled.

That works pretty well but I have the impression that the saving/export speed is limited because the json content and also corresponding images are shown in the FModel GUI.

I would appreciate an option that allow for a plain batch export/save operation without an update of the json and image window in the GUI.

**Comment by iAmAsval** [comment]
coming as a new option in **fmodel 4** when right-clicking a folder
enabling autosave will still load everything but using the right-click menu will bulk save without loading other stuff

**Comment by iAmAsval** [comment]
closing this since it's added
coming next release if next release is FModel 4

**Comment by britiscurious** [comment]
Is this functionality implemented on a hidden branch? Checked with an build from the latest code but can't find that functionality.
Right click "Save" on folders is still only for adding the path to the directory.

**Comment by NotOfficer** [comment]
> Is this functionality implemented on a hidden branch?
FModel 4 is a private repo and becomes public when its "done".
