### ISSUE TITLE
xD

### ISSUE THREAD

**Issue by i7kahmed** [iAmAsval/FModel#168]
xD
![BID_008_SkiDude_CAN](https://user-images.githubusercontent.com/72029350/111386275-1093e180-86bd-11eb-975d-8021f385926f.png)

**Comment by MaikyM** [comment]
https://discordapp.com/channels/637265123144237061/637609435329462273/821446416571301898

**Comment by FortniteLeaker21** [comment]
hey so um i saw this on FireMonkeys Channel And i want to learn more about Datamining Fortnite Datamining Nothing Else Could Someone Tell me How to Do it using Fmodel Messages thx

**Comment by iAmAsval** [comment]
> hey so um i saw this on FireMonkeys Channel And i want to learn more about Datamining Fortnite Datamining Nothing Else Could Someone Tell me How to Do it using Fmodel Messages thx

https://youtu.be/RvueeI3QSro
https://youtu.be/xji30tx0GKY
