### ISSUE TITLE
Not export / Play ADPCM File 

### ISSUE THREAD

**Issue by Sal101010** [iAmAsval/FModel#169]
Not export / Play ADPCM File 

When i play the OGG file everything is good, but in ADPCM NO play and no export.
![Capture d’écran 2021-03-17 174406](https://user-images.githubusercontent.com/80845373/111504940-63ff4180-8748-11eb-9c1e-2a00ae862324.png)

**Comment by iAmAsval** [comment]
met à jour ton fmodel https://fmodel.app/downloads/artifact/
