### ISSUE TITLE
Music extracting

### ISSUE THREAD

**Issue by RythenGlyth** [iAmAsval/FModel#17]
When i extract music or sound, it extract but it open an window with path/fmodel/Extracted/Sounds/file.ogg not found

**Comment by ItsFireMonkey** [comment]
Are you trying to extract music from the Nintendo Switch .PAK's? If so FModel doesn't currently support Nintendo Switch Audios.

**Comment by ItsFireMonkey** [comment]
Also make sure you're extracting the sound file and not the _Cue file.

**Comment by RythenGlyth** [comment]
No im on pc and i exported the normal file

**Comment by ItsFireMonkey** [comment]
Could you provide an image/video of the file you're trying to extract?

**Comment by iAmAsval** [comment]
also what program do you use to read .ogg file?

**Comment by RythenGlyth** [comment]
ah now i know the problem, i don't have a program wich can open ogg files, i drag them every time in the browser, i thinked that FModel has an own reader for ogg files.

**Comment by ItsFireMonkey** [comment]
I recommend getting "VLC Media Player" if you would a program that can open ogg files

**Comment by RythenGlyth** [comment]
yes i already have it, but i don't have it as default program for ogg
