### ISSUE TITLE
Backup Files do not load.

### ISSUE THREAD

**Issue by GabzitoZ** [iAmAsval/FModel#170]
I downloaded Fmodel version 3.0.4.3, to see the Fortnite files. But when I start the program, it loads, and then the log says "Error while checking for backup files." I can't see or download any backup file, because they don't appear to me. I've tried reinstalling FModel, but the error persists. My fortnite is up to date. What do I do?
![image](https://user-images.githubusercontent.com/80972510/111807702-ff5ff600-88b1-11eb-90f2-7efa75075143.png)

**Comment by iAmAsval** [comment]
update fmodel
this version is one year old ...
