### ISSUE TITLE
FModel Failing to Reload Mappings

### ISSUE THREAD

**Issue by Tranqua3141** [iAmAsval/FModel#171]
I was browsing the search tool finding some images of weapons and then suddenly I get the dreaded "no image" thumbnail and saw a "null" in the code. I tried pressing F12 to reload the maps and it says that the mappings have "Failed to reload". I didn't know what to do so I reset the settings, and even deleted FModel and downloaded it again and apparently got this: (See image below)
![FModel unable to reload mappings](https://user-images.githubusercontent.com/81016595/111867319-23a0fd00-89ae-11eb-8e23-a0cb45b81e41.png)

Here's the latest log:
[FModel-Log-2021-03-20.txt](https://github.com/iAmAsval/FModel/files/6175369/FModel-Log-2021-03-20.txt)

**Comment by iAmAsval** [comment]
benbot is down, just wait or update your fmodel from source
https://fmodel.app/downloads/artifact/

**Comment by Tranqua3141** [comment]
> benbot is down, just wait or update your fmodel from source
> https://fmodel.app/downloads/artifact/

How long should I wait until benbot goes up again?
