### ISSUE TITLE
FModel "Menu" Issue.

### ISSUE THREAD

**Issue by ChristianMods** [iAmAsval/FModel#172]
Hello, I recently came upon an issue with "menu placement" inside of FModel... ive never seen this before and it occurred after i decided to reinstall FModel about 2 days ago, a screenshot will be provided to show the issue. Maybe this is common and can be fixed easily but im not sure... the issue is upon opening assets\\directories\\cosmetics the menu will open towards the left and not the usual right side and with that happening the menu just completely closes when trying to scroll over to goto. im sorry if this explanation is just completely terrible but im super tired ;)
![fmodel](https://user-images.githubusercontent.com/68878422/111889222-f3f7f200-89b9-11eb-9422-f9406f98de69.png)

**Comment by iAmAsval** [comment]
https://stackoverflow.com/a/37327112/13389331

**Comment by ChristianMods** [comment]
> https://stackoverflow.com/a/37327112/13389331

i will try this. thanks for responding
