### ISSUE TITLE
Can not extract ADPCM files in bulk

### ISSUE THREAD

**Issue by angeld23** [iAmAsval/FModel#173]
1. Describe the bug
    FModel is unable to properly extract ADPCM files in bulk. When extracting an ADPCM file, it's displayed in the audio player, but MUST be clicked on in the player to be converted to `.wav` and appear in the Output folder. This only works for singular files.
2. Steps to reproduce the behavior
    In this example, I right-click the "Audio" folder in the files for Zero Crisis Finale (`FortniteGame/Plugins/GameFeatures/Yogurt/Content/Audio`) and click "Extract". 
FModel goes through all the files and extracts them, successfully extracting every `.ogg` file and placing them in the output folder. **However**, any ADPCM files that were located in the directory do not get extracted at all.
So, I try directly using Extract on a folder that contains nothing but ADPCM files (in this case, `Audio/VO/Foundation/DJ`) and click Extract. This... does nothing. All the files are basically skipped because they were never converted to `.wav` by me clicking on them in the audio player.
Two solutions I can think of: Either allow file extraction to just export as ADPCM instead of skipping the file or automatically convert to `.wav` during the bulk extraction process.

3. Send logs
    [FModel-Log-2021-03-16.txt](https://github.com/iAmAsval/FModel/files/6186167/FModel-Log-2021-03-16.txt)

**Comment by XTigerHyperX** [comment]
This isn't exactly a bug , the ADPCM to .wav conversation is supposed to start when an item is selected 

But the whole ADPCM to .wav process will improved soon

**Comment by angeld23** [comment]
Is there a way to extract ADPCM files in bulk as just ADPCM files? So I can skip the .wav conversion?

**Comment by NotOfficer** [comment]
Not without modifying the source yourself.
You can join my discord server [here](https://discord.com/invite/AqzEcMm) and use the `/export <path>` command.
