### ISSUE TITLE
FModel will no longer export sounds. 

### ISSUE THREAD

**Issue by SANSUT98** [iAmAsval/FModel#184]
I have been having lots of trouble ever since the launch of FModel V.4.0 and Fortnite V17.00 . FModel no longer extracts audio files at all. This bug is occurring with FModel V4.002 and Fortnite V17.00.  Anyone know a workaround or fix?

Edit: I have tried: A clean reinstall of FModel - Changing and confirming the correct files paths for the PAK files and Output - Switching Stable to Beta - Used slightly older versions of FModel

**Comment by iAmAsval** [comment]
Audio Player, right click, save playlist

**Comment by SANSUT98** [comment]
Thank you, that did it!
