### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Mirrorman95** [iAmAsval/FModel#192]
An unhandled exception occurred: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

I tried downloading version 13.0.1.25517 of Newtonsoft.Json.dll and putting it in the same folder as FModel v4.0.1.1, but it still gives the same error. As best as I can figure, v13.0.0 of the dll has been deprecated and is no longer available on the web, so it doesn't make sense to me to require it of FModel as a prerequisite.

**Comment by NotOfficer** [comment]
Please try to redownload the binary: https://github.com/iAmAsval/FModel/releases/download/4.0.1.1/FModel.zip

**Comment by Mirrorman95** [comment]
Thanks, that fixed it!
