### ISSUE TITLE
Search in a bnk file

### ISSUE THREAD

**Issue by Mitya11** [iAmAsval/FModel#193]
I may not have seen something, but when I open a bnk file with 7 thousand sounds, I do not know what to do. The file has more than 7 thousand sound recordings and each corresponds to its own id. Studying the game files, I find the sound id I need, but I can't just find this id in the bnk file, because there is no possibility of searching in this player. Personally, even a scroll bar would be enough for me to search. But I can't turn the mouse wheel for 5 minutes every time to find the right id,sooner or later I'll just break it. And please do not suggest using wwise unpacker, because it exports every sound while losing the id. As a result, I have a bunch of files with names from 1 to 7000+. The search is not possible. Can I export all sounds with an id from FModel at once, or at least adequately view them?

**Comment by HybridFNBR** [comment]
CTRL + F

**Comment by iAmAsval** [comment]
coming next release
or build the dev branch
