### ISSUE TITLE
cant load texture

### ISSUE THREAD

**Issue by YouKnow-sys** [iAmAsval/FModel#194]
Hi, first of all perfect project, thank you all for it. in older version (sorry I cant remember the exact version number) I could open and see texture inside of FModel, but I don't know why after updating it I can no longer open the texture inside it, its always give me

```c#
[ERR] Object reference not set to an instance of an object.
      at CUE4Parse.UE4.Assets.Exports.Texture.UTexture2D.WriteJson(JsonWriter writer, JsonSerializer serializer)
```

error and I don't know why...  
btw I tested it on a game that used **Unreal 4.20.3**

**Comment by GMatrixGames** [comment]
Did you set the unreal version to the correct one for the game you're loading?

**Comment by YouKnow-sys** [comment]
> Did you set the unreal version to the correct one for the game you're loading?

oh man...
I didn't see the option in setting before, now its all fixed. thank you for fast answer.
