### ISSUE TITLE
Error with dependencies

### ISSUE THREAD

**Issue by ElHave** [iAmAsval/FModel#195]
installed .net5 and still fmodel asking for install .net, what is happening i dont understand

**Comment by iAmAsval** [comment]
> installed .net5

then no
follow the installation process **FROM THE README** https://github.com/iAmAsval/FModel#installation

**Comment by ElHave** [comment]
Installation
To use FModel, you need to have .NET 5 installed on your computer

Download the latest release.
Extract FModel.exe somewhere on your PC and launch it


still do it and same.

**Comment by iAmAsval** [comment]
make sure it's actually installed, repair if needed
there's nothing we can do it's your pc and the popup message is from Microsoft, not fmodel
