### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ScikuVRC** [iAmAsval/FModel#199]
### Game

Dead By Daylight

### Error

```shell
An unhandled exception occurred: The invocation of the constructor on type 'FModel.MainWindow' that matches the specified binding constraints threw an exception.
```

### Reproduction steps

1. Downloaded an older manifest of DbD
2. Opened files while not done
3. Clicked reset settings on software
4. **An unhandled exception occurred: The type initializer for 'FModel.Services.ApplicationService' threw an exception.**
5. Voila, can't use the software on my end now.

**Comment by iAmAsval** [comment]
delete appdata/roaming/fmodel
and please go to the settings and choose Beta as the update mode

**Comment by ScikuVRC** [comment]
> 
> 
> delete appdata/roaming/fmodel
> and please go to the settings and choose Beta as the update mode

Deleted, software manages to start but gives me the same errors even in beta mode.

**Comment by iAmAsval** [comment]
send the log file

**Comment by ScikuVRC** [comment]
[FModel-Log-2021-09-13.txt](https://github.com/iAmAsval/FModel/files/7157611/FModel-Log-2021-09-13.txt)

**Comment by iAmAsval** [comment]
are you sure you closed FModel, deleted the settings and then opened FModel again

**Comment by ScikuVRC** [comment]
Yup, did multiple times. Will try something to see if it'll work.

**Comment by ScikuVRC** [comment]
Was able to fix it by changing directory location, and game files by calling it Dead by Daylight. Maybe old manifest broke something. Working now, thanks for quick answers.

**Comment by iAmAsval** [comment]
odd but ok, perfect then

**Comment by DaftVagabond** [comment]
I'm not QUITE sure what I did to cause this but I'm getting this error before the app will even open

"An unhandled exception occurred: The invocation of the constructor on type 'FModel.MainWindow' that matches the specified binding constraints threw an exception."

And now I can't seem to get Fmodle to run at all
