### ISSUE TITLE
An error saving texture files.

### ISSUE THREAD

**Issue by ItsFireMonkey** [iAmAsval/FModel#2]
While running in update mode using a v8.40 backup, it had generated images quite nicely and fine. At a certain point it had messed up so I went into Visual Studio 2019 to see what the issue was, it brought me to this, stating "System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'" [Line 1786 in MainWindow.cs]

A few things to note
- I gave it admin privledges
- I added it as an exception in Windows Defender
- It always happens when it gets to WID's such as "WID_Harvest_Pickaxe_TheBomb", 
- By excluding consumables & Weapons from the search, I am able to generate images easily until it gets to "Ashton-MapA", as right after that the scan stops, stating "Unexpected character encountered while parsing value: P.Path", line 0, position 0."

This issue caused FModel to stop responding, with the only options being to close or debug.
[Imgur 1](https://i.imgur.com/kFBGVFh.png)
[Imgur 2](https://i.imgur.com/kFBGVFh.png)

**Comment by iAmAsval** [comment]
Hey,

Thanks for pointing this out and all the information you provided.
I have identified the issue, the texture file was locked by something else.

I'll be pushing a fix really soon.
