### ISSUE TITLE
Modified or All New doesn't work

### ISSUE THREAD

**Issue by TheJCB** [iAmAsval/FModel#200]
Loading all works perfectly, I can see all the new cosmetics if I search for them by ID, but loading modified or all new barely shows anything. Tried this on Fortnite live and my local version, both with the same issue.

**Comment by GhostScissors** [comment]
all new is for new and all modified is for files modified

**Comment by TheJCB** [comment]
it isn't showing the new files from 18.00...

**Comment by MinshuG** [comment]
make sure you're loading 17.50's backup file
