### ISSUE TITLE
Collapse and expand sections in JSON

### ISSUE THREAD

**Issue by MrGazdag** [iAmAsval/FModel#202]
### Description

I would like to be able to collapse certain JSON objects and arrays in a property view, for example, when searching for something, it would be useful to be able to skip through unrelated sections. I think an approach similar to Notepad++'s would be appreciated:
![image](https://user-images.githubusercontent.com/44264503/133942864-827e3a41-a4f8-4b15-a903-9131110ec9bb.png)
The above array could perhaps be collapsed like this:
![image](https://user-images.githubusercontent.com/44264503/133942867-825c5255-55b9-467c-a8f7-2564b2268a56.png)

Not sure how much it would affect UI performance. The only problem i can think of currently are large JSON files.

The current workaround for this is to export the JSON, and open it in another editor, like Notepad++, which has this functionality. Implementing this directly into FModel would make it much more convenient to use FModel for viewing JSON files.

**Comment by iAmAsval** [comment]
double click the tab name

**Comment by MrGazdag** [comment]
Didn't know this functionality existed, thank you.
