### ISSUE TITLE
Animation Curves

### ISSUE THREAD

**Issue by Tectors** [iAmAsval/FModel#211]
### Description

Allow animation curves to be read and exported for purposes, by a option or some kind.

It might seem that the majority of the users won't use the animation curves, but it is still needed as a option for other uses.

**Comment by iAmAsval** [comment]
Be more clear please, I don't get it
If it's just about CUE4Parse, use the CUE4Parse repo

> It might seem that the majority of the users won't use the animation curves

what even is the curve supposed to show?
