### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by WettleTheDev** [iAmAsval/FModel#219]
### Game

None

### Error

```shell
An unhandled exception occurred: Access to the path 'C:\Windows\system32\Output\Backups' is denied.
```

### Reproduction steps

1. I open the exe.
2. I get that error
3. 
![image_2021-11-30_073944](https://user-images.githubusercontent.com/78058193/143959808-609c8767-d255-4b61-9139-270a14a1004e.png)

**Comment by XTigerHyperX** [comment]
Extract FModel and put it in a folder before using it

**Comment by WettleTheDev** [comment]
Oh. Thx. I didn't know i needed to do that.

**Comment by sirvibegodlol** [comment]
also don't launch it from the start menu, it thinks your launching from some random start menu folder and messes it up.
