### ISSUE TITLE
Bug PSA animations distort some meshes from corresponding PSK exported with fmodel

### ISSUE THREAD

**Issue by CharlieTemplar** [iAmAsval/FModel#220]
### Game

Fortnite

### Error

```shell
Exported PSA seems to distort related PSKs.
Is this a know issue?

https://user-images.githubusercontent.com/47461175/143780354-2a3f7d6a-43dd-42ae-aba5-ccace76783ee.png

https://github.com/Befzz/blender3d_import_psk_psa/files/7620949/cosmosPet.zip
```

### Reproduction steps

Export PSK and PSA from Fortnite
Import into Blender with Befzz / blender3d_import_psk_psa
Animations incorrectly deform some bones, especially facial..

![image](https://user-images.githubusercontent.com/47461175/143967643-92105123-81d6-4487-9ebc-17214d27ee96.png)

**Comment by Tectors** [comment]
Tons of heads get distorted not just this one, it's mainly heads btw.

**Comment by CharlieTemplar** [comment]
mostly lip/mouth and brow/eye parts from what I've seen.

**Comment by iAmAsval** [comment]
fixed

**Comment by Tectors** [comment]
Good job.

**Comment by CharlieTemplar** [comment]
What is fixed? Just downloaded the latest release FModel v4.2.0.0 and the same issue occurs with the model in the report.
Do I need to get a specific branch?

**Comment by Tectors** [comment]
> What is fixed? Just downloaded the latest release FModel v4.2.0.0 and the same issue occurs with the model in the report. Do I need to get a specific branch?

dev

**Comment by iAmAsval** [comment]
use 'dev' and pull cue4parse

**Comment by CharlieTemplar** [comment]
Oh well, I don't have a build environment for this.  Will the fix make it into a release?
