### ISSUE TITLE
Option To Save Meshes Without Model Viewer

### ISSUE THREAD

**Issue by Tectors** [iAmAsval/FModel#222]
### Description

One of the worst things for me on FModel's new versions is that every time you try to save a mesh you have to click two times and then click again for saving a mesh, due to the Model Viewer.

Yet even If I disable the model viewer I can't save the mesh into PSK any how.

Why was the "Save Meshes" removed in the first place?? Why when I click on a Skeleton it saves it without any other prompt but when I try saving a SkeletalMesh it prompts me to the Model Viewer.

And why is Skeletons automatically exported when extracting but not SkeletalMeshes??

My suggestion is to re-add the "Save Meshes" auto button as it was very useful and faster for exporting multiple meshes at a time without having to press a button.

**Comment by Tectors** [comment]
Let me make it shorter, why can't you export meshes without the model viewer?

And why doesn't the "you can't export skeleton meshes" not apply to skeletons, because you can export skeletons without the Model Viewer you just double click it, unlike to Skeletal Meshes.

**Comment by iAmAsval** [comment]
It will be reworked to allow users to select what to preview, what to auto-save without preview and what to not preview nor save
feel free to suggest a good UI / UX for it
