### ISSUE TITLE
Two Errors - Need Help!

### ISSUE THREAD

**Issue by DivLives** [iAmAsval/FModel#226]
`[ERR] One or more errors occurred. (Couldn't find LoaderGlobalNameHashes chunk in IoStore global.utoc)
      at FModel.ViewModels.CUE4ParseViewModel.<>c__DisplayClass43_0.<LoadVfs>b__0(CancellationToken cancellationToken)
[INF] Mappings pulled from '++Fortnite+Release-19.01-CL-18415863-Windows_oo.usmap'
[INF] 167219 localized resources loaded for 'English'
[INF] 227 virtual paths loaded
[ERR] One or more errors occurred. (Found IoStore Package but global data is missing, can't serialize)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
`

That is the whole log, the first error is there as soon as I boot up fmodel, using load method "All" and pressing load, everything works fine, whenever I try and look at anything, I get the last error message. I am using version 4.2 of FModel and I need help with this!
Thank you in advance!

**Comment by Amrsatrio** [comment]
Change game version to GAME_UE5_0 in settings or verify your files
