### ISSUE TITLE
FModel crashing on launch

### ISSUE THREAD

**Issue by MacoDeVinx** [iAmAsval/FModel#240]
### Game

Ready or Not

### Error

Gave me no error or at least i don't know where to find this error (no pop-up)

In Logs it says this (deleted for fresh log and opened FModel)

```
2022-01-06 06:16:53 [FModel] [INF] Version 4.2.0.0
2022-01-06 06:16:53 [FModel] [INF] Windows 10 Pro (64-bit)
2022-01-06 06:16:53 [FModel] [INF] .NET 6.0.1
2022-01-06 06:16:53 [FModel] [INF] Culture da-DK
2022-01-06 06:16:53 [FModel] [INF] ["GET"] [OK(200)] 'https://api.fmodel.app/v1/news/4.2.0.0'
```

### Reproduction steps

Added Ready or Not as a game preset and then it just began to crash.
Tried the following:
```
GameDirectory: K:\\SteamLibrary\\steamapps\\common\\Ready Or Not (Crash.)
GameDirectory: K:\\SteamLibrary\\steamapps\\common\\Ready Or Not\\ReadyOrNot\\Content\\Paks (Crash.)
GameDirectory: K:\\SteamLibrary\\steamapps\\common\\Ready Or Not\\ReadyOrNot\\Content\\FMOD\\Desktop (Didn't crash but nothing to select with this.)
```

I know it's not a lot of details to go out from but that is what I did for it to bug out.

**Comment by iAmAsval** [comment]
delete the small pak file

**Comment by MacoDeVinx** [comment]
Oh interesting that would do it.. Thank you :))
