### ISSUE TITLE
Enable support for multiple output folders (again)

### ISSUE THREAD

**Issue by manniL** [iAmAsval/FModel#242]
### Description

Hey 👋  https://github.com/iAmAsval/FModel/commit/f0caf246b5cae6a7b94aabfc75a2e66bc2e6ec76 removed multiple output folders (per assets category). Any chance we could have an option to "reintroduce" them? 🤔

**Comment by iAmAsval** [comment]
I thought about a dedicated setting for each category *(automated ? limited? idk yet)* when I deleted them, just like we have with models, so sure, that will come back.

**Comment by manniL** [comment]
That's great news 😋 
Should I keep the issue open then (so it can be closed with a corresponding PR that e.g. introduces these settings)?

**Comment by iAmAsval** [comment]
You can keep it open, it will be closed later today 😉

**Comment by iAmAsval** [comment]
that's it for now, we will see if it needs changes before a public release
![image](https://user-images.githubusercontent.com/26126862/148794447-db296ce9-be56-4356-828f-1d3ce39463c2.png)
