### ISSUE TITLE
Error on double click of assets

### ISSUE THREAD

**Issue by Crush0369** [iAmAsval/FModel#245]
### Game

Fortnite

### Error

```shell
Getting error on double click on uasset.

[WRN] Could not load virtual paths, plugin manifest may not exist
[ERR] One or more errors occurred. (Found IoStore Package but global data is missing, can't serialize)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

Once I loaded PAK, I go to Packages-Directories-Cosmetics-Go To

and I see a list of 1320 characters. But when i double click or try to load a uasset I get the above errors.
```

### Reproduction steps

Packages
Directories
Cosmetics
Go To

**Comment by Crush0369** [comment]
Updated software, updated and install unreal engine. Still getting errors

[ERR] One or more errors occurred. (Couldn't find LoaderGlobalNameHashes chunk in IoStore global.utoc)
      at FModel.ViewModels.CUE4ParseViewModel.<>c__DisplayClass43_0.<LoadVfs>b__0(CancellationToken cancellationToken)
[INF] Mappings pulled from '++Fortnite+Release-19.01-CL-18489740-Windows_oo.usmap'
[INF] 167231 localized resources loaded for 'English'
[INF] 227 virtual paths loaded
[ERR] One or more errors occurred. (Found IoStore Package but global data is missing, can't serialize)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

**Comment by Amrsatrio** [comment]
1. You don't need to install Unreal Engine to use FModel
2. Currently we still default to UE4, since Fortnite has moved to UE5 with the latest chapter update you need to manually change the game version in settings

**Comment by Crush0369** [comment]
ok. there are 3 possible choices for UE5, which one

**Comment by Amrsatrio** [comment]
Any of them works, it never hurts trying

**Comment by Crush0369** [comment]
lol. thank u
I picked the first one (Game_UE5_0 (536870912)
 and it worked
