### ISSUE TITLE
FModel export error. Valorant

### ISSUE THREAD

**Issue by jasmur0** [iAmAsval/FModel#254]
### Game

Valorant

### Error

```shell
[ERR] Index was outside the bounds of the array.
      at FModel.ViewModels.ModelViewerViewModel.PushLod(CMeshSection[] sections, CMeshVertex[] verts, FRawStaticIndexBuffer indices, ModelAndCam cam)
```

### Reproduction steps

1. Install Valorant 4.04
2. Tried to export Vandal SOL
3. Error
P.S Im using FModel Beta and Valorant 4.04, same situation with Stable varsion

**Comment by floxay** [comment]
Fixed in https://github.com/FabianFG/CUE4Parse/commit/a0382edc89fd9d6ee2bc958bf2ed200eab187690

 Wait for the next release of FModel

**Comment by jasmur0** [comment]
Ok, no problem. Thank you!
