### ISSUE TITLE
FModel 4.2.2.0 Does not open on Windows.

### ISSUE THREAD

**Issue by archeruwu** [iAmAsval/FModel#257]
### Game

All

### Error

```shell
When trying to launch FModel, it instantly crashes, simple as that. (3 other people in the discord with the same issue)
```

### Reproduction steps

1. download 4.2.2.0 on windows
2. try to open it

**Comment by XTigerHyperX** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer
