### ISSUE TITLE
KOF15 Support

### ISSUE THREAD

**Issue by UniversalKunn** [iAmAsval/FModel#261]
### Description

![what we get](https://user-images.githubusercontent.com/100048346/159815214-bb34792e-48f7-4ac9-8abe-fef66cd982b7.png)
![what we want](https://user-images.githubusercontent.com/100048346/159815218-cc9932f6-b0bb-4192-9fb9-06281497fedf.png)

Could you add support for KOF15's Orange_Launch.pck? It doesn't even extract via FModel, therefore we have to use quickBMS, and this makes audio extraction 20x harder.

**Comment by UniversalKunn** [comment]
> You're misunderstanding pck files
> 
> .locres have nothing to do with .pck files and fmodel support both of these files

Various people including myself  have tried ripping this file using Fmodel so we can open it in RingingBloom, but we get this error:
![see the  errors](https://user-images.githubusercontent.com/100048346/159824696-0bb32bfc-cf77-4743-9843-b8085c19fe7d.png)

**Comment by iAmAsval** [comment]
if only this .pck doesn't work, there's nothing we can do about it
it's corrupted if you can't even export it

**Comment by iAmAsval** [comment]
probably
