### ISSUE TITLE
A really weird bug

### ISSUE THREAD

**Issue by GroundPower** [iAmAsval/FModel#262]
### Game

Valorant

### Error

```shell
i got backup files on Valorant. If i select All (modified) and try to open it, it will open succesfully but if i select All (new) and try to one of my backup files it shows all folder instead of new file folders, my friend gave me a backup file and i tested it, it worked like a charm.

Backup file: https://mega.nz/file/pGBiBY4a#0Z3AhNCLFXJyIoaGyvf6z0dxR-gbJtbvwhLYh_Ngm90
```

### Reproduction steps

Create backup file on any date (for ex: 23 March pre 4.04 update)
Select backup file
Select All (new)
if i selected my file, it shows all folder like on picture
![FModel_kwgEoXiqXV](https://user-images.githubusercontent.com/16006435/159848557-1e4d7f9e-9b9b-438a-bc18-0d4ed00cd781.jpg)
if i select my friend's file, it works like a charm
![FModel_d9JZgVcxWg](https://user-images.githubusercontent.com/16006435/159848598-d4b7bafd-eca5-43a0-801e-0da47a125a68.jpg)

**Comment by GroundPower** [comment]
i tried on both language, mine and English one.

**Comment by iAmAsval** [comment]
this can only happen when your backup file was not correctly/fully created hence doesn't have all the files metadata your local archives have

**Comment by GroundPower** [comment]
> this can only happen when your backup file was not correctly/fully created hence doesn't have all the files metadata your local archives have

What should i do to fix it? Reinstall game?

**Comment by GroundPower** [comment]
i created new back-up file like 5 mins ago, when i try to open with All (new) mode, it shows all folders like this bug, it wasnt like meta-data files i think
