### ISSUE TITLE
None of models can be open in TJOC

### ISSUE THREAD

**Issue by VityaSchel** [iAmAsval/FModel#265]
### Game

The Joy of Creation: Reborn or Story mode

### Error

```shell
It's either
[ERR] One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
or
[ERR] One or more errors occurred. (NumTextureAllocations != 0)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
on ALL files (models, textures, sounds)
```

### Reproduction steps

1. Download tjoc from gamejolt (free)
2. Open the only pak game has
3. open anything inside the package

UEViewer can open models from TJoC but not sounds and maps, that's why I wanted to switch to FModel

**Comment by GMatrixGames** [comment]
Works fine when using 4.17 as the UE version instead of 4.16
![image](https://user-images.githubusercontent.com/25112532/160700893-af6257d6-0870-4863-92e3-a33bdd0c13e6.png)

**Comment by VityaSchel** [comment]
> Works fine when using 4.17 as the UE version instead of 4.16 ![image](https://user-images.githubusercontent.com/25112532/160700893-af6257d6-0870-4863-92e3-a33bdd0c13e6.png)

Thank you for response, I will try it today and close the issue if it is working!

**Comment by VityaSchel** [comment]
@GMatrixGames 
Hello, I have tried setting version to UE4_17 in settings but it didn't change anything. 

![image](https://user-images.githubusercontent.com/59040542/161066979-62a2226e-dac2-458e-b356-437350164b32.png)

I have tried opening reborn models but looking at your screenshot I noticed you opened Story Mode game, I will try it too and let you know if it worked, but I want to export map files from reborn which are exclusive to that game, not story mode. Please, try to open TJOC:Reborn.

**Comment by VityaSchel** [comment]
Thank you very much for your help, I managed to open Story Mode files in FModel

![image](https://user-images.githubusercontent.com/59040542/161071091-bcd46cb4-dbeb-473e-bf1d-aa32ad47f000.png)

I hope you can help me with opening reborn files too :)
