### ISSUE TITLE
Can't Preview Any Assets From Valorant

### ISSUE THREAD

**Issue by b1naryTR** [iAmAsval/FModel#266]
### Game

Valorant

### Error

```shell
[ERR] One or more errors occurred. (Invalid FString length '983040')
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
```

### Reproduction steps

1. Select game directory
2. Provide AES key
3. Load all archives
4. Try to open any packages

**Comment by MinshuG** [comment]
Make sure you have selected GAME_Valorant as ue version

**Comment by b1naryTR** [comment]
![image](https://user-images.githubusercontent.com/78278621/161630047-90e95ca8-2c11-4ad9-aa9a-041e2402eebe.png)
looks like FModel automaticly sellected this version, thanks for help
