### ISSUE TITLE
Issue trying to export Fortnite models...

### ISSUE THREAD

**Issue by lizardpeter** [iAmAsval/FModel#268]
Object reference not set to an instance of an object.
      at CUE4Parse_Conversion.Meshes.MeshConverter.TryConvert(USkeletalMesh originalMesh, CSkeletalMesh& convertedMesh)

I get this when I try to export a Fortnite skin. Now it is happening to multiple skins. It is the Kylo Ren M_Med_Galileo_Kayak skin.

**Comment by NotOfficer** [comment]
Is that using the latest FModel release?

**Comment by lizardpeter** [comment]
Yes, that was using the latest release.

**Comment by NotOfficer** [comment]
A fix already exist, expect a new release soon.

**Comment by lizardpeter** [comment]
> A fix already exist, expect a new release soon.

Awesome. Thanks!

**Comment by lizardpeter** [comment]
It is still not working for me, even with the latest release.
