### ISSUE TITLE
Bug  of start

### ISSUE THREAD

**Issue by Mrbleuvage** [iAmAsval/FModel#271]
### Game

All

### Error

```shell
An unhandled exception occurred: Unable to load DLL 'C:\Users\romai\Desktop\Output\.data\oo2core_9_win64.dll' or one of its dependencies: Le module spécifié est introuvable. (0x8007007E)
```

### Reproduction steps

![Capture](https://user-images.githubusercontent.com/104023268/164055293-c2592484-d9e1-43fd-b2af-e2147da32d20.PNG)

**Comment by MasterCATZ** [comment]
FModel v4.4.2.0 still has this
