### ISSUE TITLE
Skins Importing Improperly / Low Res Textures

### ISSUE THREAD

**Issue by bullzye** [iAmAsval/FModel#276]
### Game

Fortnite 

### Error

```shell
There is no specific log or error code, in the model view finder, MANY models display in low resolution DESPITE HIGH-RES TEXTURES DOWNLOADED. 
Model imports improperly with 1024 x 1024 textures instead of 2048 x 2048 for skins.
PLEASE, if there is any fix for this or an fmodel update needed, let me know!
```

### Reproduction steps

1. Model (Dino Collector) for instance imports improperly with 1024 x 1024 textures instead of 2048 x 2048.

![Screenshot (1857)](https://user-images.githubusercontent.com/96799269/166503456-b3798a93-9733-4d4e-b4f5-7c5f2545d2bb.png)
![Screenshot (1865)](https://user-images.githubusercontent.com/96799269/166503536-5cf94a1f-f1df-4552-9a15-59a8d79a42b8.png)
![Screenshot (1867)](https://user-images.githubusercontent.com/96799269/166503717-6762378b-f2c3-4f15-85b0-3b63ebdd304b.png)

**Comment by MinshuG** [comment]
https://github.com/iAmAsval/FModel/commit/b319d9d89e7e4ba9efca2c3f31ff7c978bcdccc3 already fixed. 
Downloading high resolution textures from Epic Games Launcher won't get you the resolution you are looking for. They are downloaded by **game** itself on **demand**.

**Comment by bullzye** [comment]
How I download high res textures from the game itself? I'm quite confused on this issue as this is happening to many others who use the fmodel exporter.

**Comment by Amrsatrio** [comment]
See the skin yourself. One way would be through a private server

**Comment by bullzye** [comment]
How would downloading the files from a private server fix the issue? Is this export issue on epics side or an fmodel issue? Thank you for helping, although I don't quite understand how to fix.

**Comment by iAmAsval** [comment]
you have to make your game load the skin so that it downloads the HR textures I guess
only then fmodel will be able to use it
