### ISSUE TITLE
Fmodel wouldn't open (4.2.2.1)

### ISSUE THREAD

**Issue by MasterMRL** [iAmAsval/FModel#278]
### Game

Nothing. Just Fmodel problem

### Error

```shell
I was trying to open Fmodel's new version. but It wouldn't run. I don't know why it wouldn't run.
Fmodel: 4.2.2.1
I had to download the Fmodel's old version then they're working. It seem that Fmodel's new version will not open.
```

### Reproduction steps

just tries to open Fmodel.exe then nothing happens. it refuse to run the game. I did run it as admin.
4.2.2.1 is bugged.
the old versions are working. Fmodel's old versions will run and they're fine working.

**Comment by MasterMRL** [comment]
Why did you closed this?
I was hope that you could help out. But you decide to close for no reason without providing help and explanation?
I have been trying to run the new version since it got released. But App will not open itself.
I don't know what's wrong with the new version.

**Comment by Amrsatrio** [comment]
https://github.com/iAmAsval/FModel/issues/257#issuecomment-1073246893

**Comment by MasterMRL** [comment]
Oh, it's working. Thanks for help!
