### ISSUE TITLE
Latest Version not launching.

### ISSUE THREAD

**Issue by Bentheminernz** [iAmAsval/FModel#279]
### Game

Fortnite

### Error

```shell
I've updated FModel to latest version and now all of a sudden it refuses to open... I tried updating it using the built in tool and downloading a clean version from the GitHub page but now will launch. The mouse will turn to the blue spiny circle as if its opening FModel but then nothing happens. I decided to download the old version to see if it is a problem with the latest version and sure enough it still launches! So I don't believe its a problem with my computer... I even tried launching as a administrator and it still didn't work...
```

### Reproduction steps

1. Open the latest version of FModel
2. Now it shouldn't open at all

**Comment by Bentheminernz** [comment]
Why did you instantly close it?

**Comment by iAmAsval** [comment]
duplicate of https://github.com/iAmAsval/FModel/issues/278
duplicate of https://github.com/iAmAsval/FModel/issues/257
explained on discord since the release
![image](https://user-images.githubusercontent.com/26126862/168762101-ccf5ed63-1c67-40d7-8242-fb6d011f3146.png)
