### ISSUE TITLE
Watermark is very choppy

### ISSUE THREAD

**Issue by archeruwu** [iAmAsval/FModel#33]
3.0, The watermark is very buggy, 
![image](https://user-images.githubusercontent.com/18449883/67641220-fe05e600-f8d6-11e9-915d-b96cf07e1502.png)
and looks pretty bad

**Comment by iAmAsval** [comment]
i'm already working on a fix for this issue 🙂

**Comment by iAmAsval** [comment]
[FModel.zip](https://github.com/iAmAsval/FModel/files/3776619/FModel.zip)
can you try with this one and let me know if it's fixed

i can already confirm it's fixed for large watermarks, but it looks aliased with small watermarks, what do you think?

**Comment by archeruwu** [comment]
Sorry for not seeing this sooner, but yes, this works, and its fixed.
