### ISSUE TITLE
Open Image and Extract buttons should be greyed out if not possible

### ISSUE THREAD

**Issue by lyndmi** [iAmAsval/FModel#37]
It's quite confusing. Some files like cue related can't open as image and extract but the buttons are still click able. Clicking on it does nothing. They should be greyed out so that we know it can't be opened or extracted

And it would be nice if the file list are colored like this when it's openable

![image](https://user-images.githubusercontent.com/24647715/71630473-76549480-2c03-11ea-97eb-bff7a71266d4.png)

**Comment by iAmAsval** [comment]
Wdym Cue assets can be extracted, everything is extractable, even if there was something unextractable there's no way to check if every assets can be extracted or not and filter them.
Also, if you don't see any image after extracting an asset, obviously `Open Image` won't work, is disabling it really needed?
