### ISSUE TITLE
add the full body item shop icons

### ISSUE THREAD

**Issue by onepumpzbtw** [iAmAsval/FModel#40]
add the full body item shop icons like here https://drive.google.com/open?id=1FLEXuHE4lGKRwHt_2IoqeTHUT25JHquQ

**Comment by iAmAsval** [comment]
this kind of icon doesn't exist in the files

**Comment by iAmAsval** [comment]
maybe for some skins
but they must be auto-detected (which isn't the case atm) and also that's not their purpose
