### ISSUE TITLE
[Suggestion] Discord Rich Presence

### ISSUE THREAD

**Issue by RushWTF** [iAmAsval/FModel#42]
My suggestion is that FModel has its own discord rich presence that is to say that your state of discord can tell you for example that you are with FModel in such a Pakchunk is exporting a cosmetic or challenges, I think that can be a good suggestion

**Comment by iAmAsval** [comment]
this will most likely come in 3.1.0

**Comment by iAmAsval** [comment]
[done](https://i.imgur.com/OeyeFhI.png)
