### ISSUE TITLE
PUBG

### ISSUE THREAD

**Issue by moisoni97** [iAmAsval/FModel#43]
Any chance to support PUBG?

**Comment by iAmAsval** [comment]
FModel is updated regularly only because we are still playing Fortnite, close enough to the game to understand what could be good for users and leakers and I believe that's why it became quite popular.

So probably not, from me at least, because I don't have PUBG, I don't know the game enough to create something for it but it's an open way for others

**Comment by moisoni97** [comment]
Ok. Thanks!

**Comment by FunGamesLeaks** [comment]
In theory the json viewer should work, maybe even sounds and textures, depending on which formats they use

**Comment by moisoni97** [comment]
I thought the same and tested it before opening the issue but, the AES key is hardcoded to start with `0x` while PUBG AES key has a different format. Maybe I am wrong and AES key can be changed, I didn't do the research I've just quickly check.
In my particular case, I've only needed a DataTable object of items rarity but I have found a different solution.
UEViewer is a similar tool but it can't extract DataTable object or 'uncooked assets'.

**Comment by FabianFG** [comment]
No probably it's just base64 encoded, if it ends with a = you can just decode it in any only tool

**Comment by moisoni97** [comment]
Yes, you are right, I didn't express myself well, I meant that FModel automatically add `0x` before the AES key

**Comment by iAmAsval** [comment]
`0x` is only visual

I googled `PUBG aes encryption key` and saw keys without this 0x, you can still use them with FModel (when you save the key in the AES Manager, it doesn't even save this 0x, so...)

**Comment by moisoni97** [comment]
I have tried it again and the output is `The file magic is invalid`, the AES Key I have worked in UEViewer so the key isn't the problem

**Comment by ItsFireMonkey** [comment]
I've actually attempted to use Fmodel in a non Fortnite game before and got the same error. But based on what UModel and QuickBMS can do I don't think FModel would be super useful for non Fortnite games because there isn't that much of a benefit from what other programs can already do.

**Comment by FabianFG** [comment]
Yeah I remember pubg had some difference in the pak files
