### ISSUE TITLE
AES api problem

### ISSUE THREAD

**Issue by MaxTechnics** [iAmAsval/FModel#45]
The benforth AES api is either down or has moved. Fmodel is unable to fetch any new AES keys.

**Comment by iAmAsval** [comment]
FModel fetch the new endpoints if you use the latest version
Only the link `Latest Fortnite AES Keys` isn't updated for the prod version but you only have to click `Reload AES Keys` to update them

**Comment by MaxTechnics** [comment]
Ok, Thank you!
