### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by jose89fcb** [iAmAsval/FModel#49]
I am translating the program into Spanish, my question is, when you update the program, could it affect the translations?
______-
Estoy traduciendo el programa al español, mi pregunta es, cuando actualizes el programa, ¿podría afectar  a las traducciones?

**Comment by iAmAsval** [comment]
Yes i guess, it depends on how you do it. You may have conflicts while pulling the latest version.

**Comment by jose89fcb** [comment]
> Sí, supongo, depende de cómo lo hagas. Puede tener conflictos al extraer la última versión.


I'm just replacing the texts, some way so that it doesn't affect the translation?
______
Sólo estoy reemplazando los textos, alguna forma para que no afecte a la traducion?

https://i.imgur.com/rUApuxp.png

**Comment by iAmAsval** [comment]
It should be good for the moment 👍

**Comment by MaikyM** [comment]
Hola, en FModel 3.1 ya estarán incluidas las traducciones en español, por lo que no tendrás más problema por ello, por ahora seguirás teniendo problemas ya que todo el programa será reemplazado junto con sus textos en cada actualización.
