### ISSUE TITLE
Api/aes

### ISSUE THREAD

**Issue by Lisenokmrr** [iAmAsval/FModel#50]
The site from which I used to take the key no longer works. benbotfn.tk/api/aes Tell me where can I get the key now?

**Comment by FabianFG** [comment]
benbotfn.tk/api/v1/aes

**Comment by Lisenokmrr** [comment]
Thanks for the link. Another question. I just inserted "mainKey" and it says "doesn't work with the main pak files", are they not updated?

**Comment by FabianFG** [comment]
The key is updated, your game probably isn't

**Comment by Lisenokmrr** [comment]
yes for sure, thank so much!
