### ISSUE TITLE
AES Key

### ISSUE THREAD

**Issue by FortntemKID** [iAmAsval/FModel#52]
please add a new website for AES keys!!!! 5*****

**Comment by MyNameIsDark01** [comment]
https://benbotfn.tk/api/v1/aes

I think it will be added in the next update

**Comment by FabianFG** [comment]
It is already in, just update your Fmodel

**Comment by iAmAsval** [comment]
the "Latest Fortnite AES Keys" button isn't up to date, I'm aware
