### ISSUE TITLE
It doesnt work please help

### ISSUE THREAD

**Issue by marto05** [iAmAsval/FModel#53]
when i try to load the PAK's it just says that the AES's key doesn't work. 
![unknown](https://user-images.githubusercontent.com/63332784/81572124-7f245680-93ab-11ea-876b-6edd3cdb905f.png)

**Comment by iAmAsval** [comment]
probably because you don't play the game so he's not up to date

**Comment by marto05** [comment]
I don't know the button for the newest key doesn't work for me the page does not load.
And I played last night Idk

**Comment by marto05** [comment]
I tried to start the game and try again but nothing has changed.

**Comment by iAmAsval** [comment]
then you have Fortnite installed twice somewhere else
there are no pak1001 since at least 2 updates

**Comment by iAmAsval** [comment]
Delete your current pak files path and restart

**Comment by marto05** [comment]
Thanks now it works but I don't understand why the pictures on the right are not loading when I select file

**Comment by iAmAsval** [comment]
https://youtu.be/1WuZML_zzEI?t=735
