### ISSUE TITLE
Ver 3.1: Chinese word characters cannot show properly

### ISSUE THREAD

**Issue by mafialong** [iAmAsval/FModel#54]
There might be issues with Chinese characters shown in GB Codes (for Simplified Chinese) or Big5 Codes (for Traditional Chinese) in version 3.1
There wasn't such issue in previous version of 3.04

The attached image is what it looks like when Simplified Chinese is selected as default language. (See the "blocks" in red circles)

![1](https://user-images.githubusercontent.com/52643936/81961637-a0ba5380-95e0-11ea-93fc-c480df6aa218.PNG)

**Comment by iAmAsval** [comment]
I'll take a look at it, thanks for the report

**Comment by iAmAsval** [comment]
looks like I swapped fonts between the 2 Chinese
can you try with this [FModel.zip](https://github.com/iAmAsval/FModel/files/4629867/FModel.zip)

**Comment by mafialong** [comment]
Now it's shown properly with the one in the zip file.
I guess it's the font that makes the difference.

Thanks!

![2](https://user-images.githubusercontent.com/52643936/81964430-91d5a000-95e4-11ea-8663-1c17823167b3.PNG)
