### ISSUE TITLE
Where is Difference Mode???

### ISSUE THREAD

**Issue by WrittenInHTML** [iAmAsval/FModel#59]
Hey there,

I am a Fortnite leaker. When I try to look at new and modified files by going to Files > PAK > Load New and Modified Files, selecting the backup that I downloaded, and waiting a few seconds, the indicator at the bottom right of the window says 'Success', but nothing pops up. Why is this??

Thanks for your time :)

**Comment by iAmAsval** [comment]
Comparing the current version against the current version will not work obviously
use an older backup...

**Comment by WrittenInHTML** [comment]
I should have clarified, but I did select an older version backup (12.50) when trying to review new and modified files.

**Comment by iAmAsval** [comment]
afaik we are in 12.50

**Comment by iAmAsval** [comment]
you should select the n-1 backup file

**Comment by WrittenInHTML** [comment]
What is the n-1 file?

**Comment by WrittenInHTML** [comment]
We are in 12.51 by the way

**Comment by iAmAsval** [comment]
12.41

**Comment by iAmAsval** [comment]
no latest update was ++Fortnite+Release-12.50-CL-13193885-Windows

**Comment by WrittenInHTML** [comment]
Oh ok, but how do I download an n-1 file?

**Comment by iAmAsval** [comment]
download the backup where the version displayed in the name is before the current one
that's n-1 means

**Comment by WrittenInHTML** [comment]
Ok, thanks so much! I guess i was downloading the wrong file! :0
