### ISSUE TITLE
Add update mode back

### ISSUE THREAD

**Issue by Twin1YT** [iAmAsval/FModel#60]
could you add back when it would save all the icons in update mode?

**Comment by iAmAsval** [comment]
Changelog says
### Removed
- Update Mode
    *- Not used the right way, this wasn't designed to extract icons because you don't know where they are*
    *- Update Mode users were not leakers, FModel was doing all the stuff*
    *- Feel free to use the new `Directories` feature as a replacement*

you can argue it was cool because you only had to select and wait, but that wasn't what I was looking for when coding it

**Comment by Twin1YT** [comment]
Ok. I found a feature similar to this on fmodel. Thank you.
