### ISSUE TITLE
Aes

### ISSUE THREAD

**Issue by Lisenokmrr** [iAmAsval/FModel#62]
https://benbotfn.tk/api/v1/aes website does not work, maybe you changed the link again? If so, can I have a new link please?

**Comment by iAmAsval** [comment]
https://fnbot.shop/api/aes
https://fortnite-api.com/aes

**Comment by iAmAsval** [comment]
benbot api is down atm

**Comment by Lisenokmrr** [comment]
Thank you, is there a place where you send a link when you change it, a Discord or something else?

**Comment by iAmAsval** [comment]
https://discord.gg/fdkNYYQ

**Comment by Lisenokmrr** [comment]
Thank you!
