### ISSUE TITLE
FModel crashes when downloading backups

### ISSUE THREAD

**Issue by real-baiblade** [iAmAsval/FModel#66]
When I try to download the latest backup to compare the files, FModel crashes for no apparent reason and when reopened, it no longer compares files.

**Comment by AyeTSG** [comment]
This works fine for me with the latest release, what version of FModel are you using?

**Comment by real-baiblade** [comment]
I was using the version recommended by iFireMonkey I believe it is version
3.0.4.3

**Comment by iAmAsval** [comment]
it crashes because i deleted 12.40 and 12.50 backup files because, since you're asked to update, you're not supposed to use 3.0.4.3
