### ISSUE TITLE
[Suggestion] Playlist Icon Generation

### ISSUE THREAD

**Issue by AyeTSG** [iAmAsval/FModel#67]
Should we add a way to generate icons for playlists? If so, I feel like we should exclude playlist descriptions due to the size of them normally. Also, it would be ideal to either grab the proper playlist image from the API, host our own playlist image API (since not all of them exist on the Fortnite API anymore), or use a placeholder icon for playlists. @iAmAsval Do you think we should implement this?

**Comment by iAmAsval** [comment]
it's a bit of work but yes definitely

**Comment by ItzGoldenFN** [comment]
Yey

**Comment by GMatrixGames** [comment]
I currently have a bunch of the playlist images hosted on my domain. If this ever comes to fruition feel free to use it! Just DM me on discord I can get you the link.

**Comment by GMatrixGames** [comment]
*Also, if anyone that knows PHP Rest API stuff, I'd like to be able to work with you to make this an API that can allow access through GET requests for specific images through arguments.

**Comment by NotOfficer** [comment]
added: 54d2ccf090ea2a062789414a040db73088235848
