### ISSUE TITLE
FModel

### ISSUE THREAD

**Issue by hacker11415151** [iAmAsval/FModel#68]
My FModel keeps saying that I need to install .NET Core when I already have it installed.

**Comment by iAmAsval** [comment]
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer

**Comment by hacker11415151** [comment]
I already have that installed

**Comment by iAmAsval** [comment]
hacker11415151, you most likely installed the sdk, you don't need the sdk you need the desktop runtime version

**Comment by hacker11415151** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/60560163/83443606-a781fc80-a40f-11ea-9478-e6038633113d.png)
Is that not the right file?

**Comment by iAmAsval** [comment]
it is

**Comment by hacker11415151** [comment]
Yeah I already have that installed

**Comment by iAmAsval** [comment]
well then idk, it should work
maybe restart your computer after installing it or restart fmodel

**Comment by hacker11415151** [comment]
I installed it like 3 days ago but thanks for trying to help.

**Comment by iFireMonkey** [comment]
Hey! I was actually having the same issue despite having everything required. Oddly enough installing and compiling the newest Master Branch [Commit 351 | "FModel x Ramirez"] fixed the issue I was having with it telling me that .NET wasn't installed.

**Comment by Noob8888** [comment]
Hey, I'm kinda a noob, so could you clarify how you did that to fix the problem? Because I also have the same issue with it telling me .NET wasn't installed.

**Comment by hacker11415151** [comment]
ye i got mine to work to
