### ISSUE TITLE
Won’t run

### ISSUE THREAD

**Issue by zrixy** [iAmAsval/FModel#69]
I downloaded net core and everything and opened it and it worked fine but when i closed it and open again it just won’t run. I click run and it will load for a bit but nothing will happen. Is there anything I can do to fix this?

**Comment by iAmAsval** [comment]
make sure you installed .NET Core 3.1 and the desktop runtime version

**Comment by iAmAsval** [comment]
i don't understand everything, you opened it, it worked but then you close it and it doesn't work anymore?
`I click run` - Run ?
`it will load` - how can you tell it loads ?

is this an issue about launching FModel or loading pak files ?

**Comment by zrixy** [comment]
I'm sorry I realized how confusing that was but I found it out and fixed it. I'm sorry for being confusing

**Comment by iAmAsval** [comment]
no problemo
