### ISSUE TITLE
Fmodel not run

### ISSUE THREAD

**Issue by PowerG75ru** [iAmAsval/FModel#70]
Fmodel not run. What's happening: [https://drive.google.com/file/d/14UWCQpNugpyUIBL_G8C1VkzWLsgXL5t3/view?usp=sharing](Video)

**Comment by simsnet** [comment]
Try installing the .NET Core 3.1 Desktop Runtime.  When I updated FModel it required me to download:

[link](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.4-windows-x64-installer)

**Comment by PowerG75ru** [comment]
Installed, all the same not running

**Comment by iAmAsval** [comment]
if it does nothing that means you have .NET Core but not 3.1
maybe try to uninstall and reinstall .NET Core

**Comment by PowerG75ru** [comment]
Nothing happens(

**Comment by iAmAsval** [comment]
https://github.com/iAmAsval/FModel/issues/72#issuecomment-640071990

**Comment by PowerG75ru** [comment]
![image](https://user-images.githubusercontent.com/66346104/83947278-3ba0f900-a840-11ea-9917-fdfadcb27e56.png)

**Comment by iAmAsval** [comment]
well idk
try to install the sdk one
run fmodel as admin
or uninstall and reinstall 3.1.4 runtime

**Comment by PowerG75ru** [comment]
installed sdk, not running, even with admin

**Comment by iAmAsval** [comment]
I personally have
```cmd
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
``` as installed runtimes

**Comment by PowerG75ru** [comment]
Delete SDK, installed 3.1.2, not running. What other options?

**Comment by iAmAsval** [comment]
i don't know

**Comment by PowerG75ru** [comment]
3.0.2.0 running. 3.1.0.4 not running. what could be the problem in new version?

**Comment by iAmAsval** [comment]
try this
[FModel.zip](https://github.com/iAmAsval/FModel/files/4746473/FModel.zip)

**Comment by PowerG75ru** [comment]
3.1.0 running

**Comment by iAmAsval** [comment]
Can you confirm it's fixed?

**Comment by Arturo83** [comment]
Same issue. Comment #78 works.
Is there is fix for Fmodel 4.x? I  need to extract UE5 models.
Thanks

**Comment by 4sval** [comment]
https://github.com/iAmAsval/FModel/issues/257#issuecomment-1073246893

**Comment by Arturo83** [comment]
> [#257 (comment)](https://github.com/4sval/FModel/issues/257#issuecomment-1073246893)

I installed sdk-6.0.201-windows-x64-installer from comment #257 +  Windows reboot. Same issue.

I found the solution for my issue by changing the Windows environment variables **DOTNET_ROOT**
_from_
D:\EPIC UE4\UE_5.0\Engine\Binaries\ThirdParty\DotNet\Windows
_to_
C:\Program Files\dotnet\
