### ISSUE TITLE
Fmodel don't launched

### ISSUE THREAD

**Issue by SimonBData** [iAmAsval/FModel#72]

**Comment by FabianFG** [comment]
[https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer)
Make sure you have exactly this one installed, not the SDK

**Comment by SimonBData** [comment]
I made sure

**Comment by FabianFG** [comment]
What happens when you try to launch?

**Comment by SimonBData** [comment]
Nothing 😪

**Comment by PowerG75ru** [comment]
Same problem, run and nothing. .NET Desktop Runtime installed.

**Comment by iAmAsval** [comment]
make sure 3.1.x or newer is installed under `.NET Core runtimes installed:` or even `.NET Core SDKs installed:` if you wanna be sure
https://www.ntweekly.com/2018/03/04/check-net-core-version-installed/

**Comment by D3ATHBRINGER13** [comment]
thanks for linking that
found out i had four different versions installed

**Comment by GhostScissors** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer download this and install
