### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EmpyreanRaps** [iAmAsval/FModel#74]
Every time I try to open my files or every time I open FModel in general it says "(I'm not going to share my aes key but my aes key is what is says) is not working with your PAK files." I followed a tutorial and theirs worked fine so I don't know how to solve my problem.

**Comment by D3ATHBRING3R13** [comment]
The AES key is the same for everyone and is not private

**Comment by iAmAsval** [comment]
if it says not working, it's because it's not working
i bet you're using it for fortnite so if your game is up to date the key is `0x3F3717F4F206FF21BDA8D3BF62B323556D1D2E7D9B0F7ABD572D3CFE5B569FAC`
