### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by 1puf** [iAmAsval/FModel#75]
my problem is : ((Unable to read beyond the end of the stream))

how i fix it?

Thanks

**Comment by iAmAsval** [comment]
we might need more informations

**Comment by 1puf** [comment]
![pr](https://user-images.githubusercontent.com/60852614/83979327-45952b80-a916-11ea-9731-d2dd2b315c00.PNG)

**Comment by iAmAsval** [comment]
what did you do before
when this happened
what game
what file
etc

**Comment by 1puf** [comment]
![Desktop 2020 06 07 - 23 32 22 04](https://user-images.githubusercontent.com/60852614/83979497-7a55b280-a917-11ea-9b11-9217e2c7c556.gif)

**Comment by iAmAsval** [comment]
compressed backup files will not work with the old FModel

**Comment by 1puf** [comment]
Oh sorry 

Thanks,
