### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by A93Nt22** [iAmAsval/FModel#76]
when i download Fmodel i only downloads the application and not the extention

**Comment by iAmAsval** [comment]
what

**Comment by A93Nt22** [comment]
when i download FModel 3.1.0.4 it doesn't download the libSkiaSharp.dll

**Comment by iAmAsval** [comment]
you don't need that anymore

**Comment by A93Nt22** [comment]
oh well thanks i did just start so i didn't know

**Comment by iAmAsval** [comment]
np
