### ISSUE TITLE
Difference and Update Mode in FModel

### ISSUE THREAD

**Issue by aLExGO18** [iAmAsval/FModel#79]
Hey, I got a question about the redesign of Fmodel. Is it still possible to save several files at once like it was possible with Difference and Update Mode in an old version of FModel? If so, could you please explain how it works? Thank you and have a nice day!

**Comment by rayanelhadi** [comment]
Update mode was removed but difference mode is still there to enable it go to FILES  then PAKS click on LOADING MODE and select NEW FILES

**Comment by iAmAsval** [comment]
![image](https://user-images.githubusercontent.com/26126862/84742037-336b5b00-afb0-11ea-833c-4026abdc2c18.png)

**Comment by aLExGO18** [comment]
> Update mode was removed but difference mode is still there to enable it go to FILES then PAKS click on LOADING MODE and select NEW FILES

So, is there any new feature that replaced the update mode or do I have to save every single file separately?

**Comment by rayanelhadi** [comment]
there are directories

**Comment by iAmAsval** [comment]
you can just extract a folder with auto save image enabled

**Comment by aLExGO18** [comment]
Thanks for your answers! I can work with this information.
