### ISSUE TITLE
FModel Again not running.

### ISSUE THREAD

**Issue by PowerG75ru** [iAmAsval/FModel#80]
FModel again not running. Installed .NET SDK 3.1.301

**Comment by iAmAsval** [comment]
you don't need the sdk
try this 
[FModel.zip](https://github.com/iAmAsval/FModel/files/4790823/FModel.zip)

**Comment by PowerG75ru** [comment]
Thanks. but: when starting sound, it happens: 
![image](https://user-images.githubusercontent.com/66346104/84869947-def7d680-b0a8-11ea-8ead-31c90def134c.png)

**Comment by iAmAsval** [comment]
I'm pretty sure what's the issue but I thought i fixed it with this zip file
just in case can you send the latest log file pls
