### ISSUE TITLE
Fmodel - .net core installed but still won't run.

### ISSUE THREAD

**Issue by Nanikoss** [iAmAsval/FModel#81]
Seen lots of other people having the exact same issue and I'm having it aswell. I have...

1. Tried using latest version and the previous release

2. Checked to make sure I definitely have .net core installed. I have the SDK for (86x) which includes the desktop runtime and .net core runtime which are all at version 3.1.5

![image](https://user-images.githubusercontent.com/35498189/84895491-b7732f00-b0e5-11ea-8c34-446e24dde022.png)

3. Also tried running both of those as administrator. 
4. Tried Uninstalling and reinstalling, no change.
5. Remembered SDK is only actually needed if you are building apps in Visual Studio. Uninstalled SDK and installed stand alone runtime, still no change.

Still get that same error upon trying to run.

**Comment by rayanelhadi** [comment]
Try this https://cdn.discordapp.com/attachments/637610061186727956/722517945095290921/FModel.zip

**Comment by Nanikoss** [comment]
Yep tried those links I've seen on prior issue posts. Also tried downloading previous releases already, still nothing. (I've talked to you on discord already a bit regarding this but yeah still nothing)

**Comment by rayanelhadi** [comment]
it's a tool for a 64 bit game so it would obviously not support 32
