### ISSUE TITLE
[BUG] FModel not opening

### ISSUE THREAD

**Issue by Animelici804** [iAmAsval/FModel#86]
Even if I install NET. Core 3.1, it doesn't work at all. I need to find a quick reason why.

**Comment by iAmAsval** [comment]
Make sure you installed the Desktop Runtime version https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer
If you still get the error, launch this once https://www.dropbox.com/s/44rajmuvyi9chaw/FModel.zip?dl=0

**Comment by Animelici804** [comment]
> Make sure you installed the Desktop Runtime version https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer
I already installed it, and the original version still didn't work.

> If you still get the error, launch this once https://www.dropbox.com/s/44rajmuvyi9chaw/FModel.zip?dl=0
The version you gave worked. Thanks.

**Comment by lynrayy** [comment]
The same. It used to open, at some point it stopped. Downloading a new file does not help, it does not open.
