### ISSUE TITLE
Launch error "Addition text encountered after reading JSON content: 3. Path '', line 1, position 2048:"

### ISSUE THREAD

**Issue by FFTeaDoc** [iAmAsval/FModel#87]
![image](https://user-images.githubusercontent.com/67734195/86336992-307f9400-bc59-11ea-8c5c-0d0f0ed85d7d.png)
I can't launch Fmodel because appears that error. What i need to do?

**Comment by rayanelhadi** [comment]
delete appdata/roaming/fmodel and appdata/local/asval/

**Comment by FFTeaDoc** [comment]
lol, it's works. Thank you very much)
