### ISSUE TITLE
2 Extraction feature requests

### ISSUE THREAD

**Issue by jhall39** [iAmAsval/FModel#88]
1) When extracting files like the sounds, can you add an option to extract into the same path structure? Instead of putting everything into the same directory, it'd be nice to have it go into "Output\Path1\Path2\Path3\file"

2) When opening some uasset files it shows a json output in the top middle window. Is there any way to extract those in that format? It would be great if those could be extracted into the same path structure as in the pak as well.

**Comment by rayanelhadi** [comment]
Good idea and to save JSon files click on save and it'll save as JSON

**Comment by iAmAsval** [comment]
coming next release
