### ISSUE TITLE
Issue when extracting a lot of files

### ISSUE THREAD

**Issue by RadonRaph** [iAmAsval/FModel#89]
I need to extract all the sound files from Fornite, when a click on the sounds folder and right click > Extract the extraction process start but it crash shortly after i think a file is corrupt or unsupported by the extractor but it could be great that the extraction process continue because if i miss one or two files i don't care :)

**Comment by iAmAsval** [comment]
keep in mind it's not designed to do this and should absolutely not used to do this but I can say "fixed next release"
I canceled it at 7000 sounds successfully extracted so it should work with the whole folder
![IewvJDcB1x](https://user-images.githubusercontent.com/26126862/86392372-a278cd00-bc9b-11ea-85b8-1a68cb5922f0.gif)

**Comment by RadonRaph** [comment]
Hello you can see here my error: 
![image](https://user-images.githubusercontent.com/38112654/86448841-a1858100-bd17-11ea-983d-8c2e0e8492eb.png)
Thats not always the same file. As i know there is 30 000 sounds in Fornite in the previous season (exported with your tool). I know this is not intended to do so much work but i study how game use sounds (How they mix them, spatialize ...) and i know for sure i'm not the only one to use it this way. Your tool is very great and saved me a lot of time more if it will work completly with Valorant and Dead by DeadLight (can't extract all the sounds for now with Fmodel too, but on Fornite it once worked) 
Some tools for other game like the Legion extractor for Apex (https://wiki.modme.co/wiki/apps/Legion.html) have an options for "Extract all" and this is very usefull.
I've liked your work and if i make this ticket is only for suggesting that some people use your tool with heavy loads :) 
Sounds scraping is a real thing with a lot of people working on it. 
Thanks in advance for your work,
Raph

**Comment by iAmAsval** [comment]
Are you trying to export the raw data or save the sound itself

**Comment by RadonRaph** [comment]
The sound itself

**Comment by iAmAsval** [comment]
Then it will work with Fortnite

**Comment by RadonRaph** [comment]
Ok a will wait the new version without the "stuck" bug that i mentionned at first, thanks for the fast replies !
