### ISSUE TITLE
How to play .pck audio files?

### ISSUE THREAD

**Issue by Noob8888** [iAmAsval/FModel#90]
I was wondering how to play audio files in general, but the ones I'm looking to play are .pck files so that might help in an explanation.

Thanks!

**Comment by NotOfficer** [comment]
https://github.com/Vextil/Wwise-Unpacker

**Comment by Noob8888** [comment]
thanks

**Comment by iAmAsval** [comment]
I have to find out how they work first and change the audio player a bit because one pck file isn't one sound

**Comment by Noob8888** [comment]
ah ok thanks

**Comment by iAmAsval** [comment]
coming next release

**Comment by Noob8888** [comment]
oh wow thanks
