### ISSUE TITLE
FModel still asks to download .NET core even after downloading it.

### ISSUE THREAD

**Issue by EndofUfff** [iAmAsval/FModel#92]
When going to your installation page, you put a link to the download page for .NET core 3.1 and when installing it, FModel still does not run and gives same message of "To run this application, you must install .NET core"

**Comment by rayanelhadi** [comment]
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.3-windows-x64-installer

**Comment by EndofUfff** [comment]
Yeah I've already tried that. It's giving me the same error that I need to install NET core even though I installed it.

**Comment by iAmAsval** [comment]
https://www.dropbox.com/s/xgm0z84d4nypxe9/FModel.zip?dl=0

**Comment by EndofUfff** [comment]
Thanks that worked.
