### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by YeezeeYeetie** [iAmAsval/FModel#93]
When I double click Fmodel it doesnt open what so ever and i have everything downloaded that has to be and even when I run it as admin doesnt open, I restarted my pc and the same issue

**Comment by rayanelhadi** [comment]
1. Press Windows+R
2. Type %temp% and enter
3. Go inside the .net folder
4. Delete the FModel folder
5. Launch FModel.exe

**Comment by YeezeeYeetYT** [comment]
How do I find the water level changes do I use FModel or Umodel and whats the path

**Comment by GMatrixGames** [comment]
You'd use FModel, and what shows the changes is in the latest pak that gets decrypted. Currently, the newest map change is in pakchunk1013
