### ISSUE TITLE
.NET Core broken

### ISSUE THREAD

**Issue by SpecterFXXK** [iAmAsval/FModel#94]
Description: A .NET Core application failed.
Application: FModel.exe
Path: C:\Users\SpecterSPX\Desktop\FModel\FModel.exe
Message: The application to execute does not exist: 'C:\Users\SPECTE~1\AppData\Local\Temp\.net\FModel\2z5mzui2.f3f\FModel.dll'.

the app was working fine last month wtf?

**Comment by SpecterFXXK** [comment]
apparently deleting everything in temp folder fixes it?

**Comment by iAmAsval** [comment]
https://github.com/dotnet/runtime/issues/3778#issuecomment-631268222

**Comment by iAmAsval** [comment]
**If overnight, FModel doesn't open anymore**
1. *Press Windows+R*
2. *Type `%temp%` and enter*
3. *Go inside the `.net` folder*
4. *Delete the FModel folder*
5. *Launch FModel.exe*

*Fixed in next release*

**Comment by SpecterFXXK** [comment]
I did that, glad to see that it's fixed in the next release, keep up the great work!
